import type { MockDb } from "./types";

export const seedDb = (): MockDb => {
  return {
    schemaVersion: 2,
    users: [
      {
        id: "u_customer_1",
        userId: 1,
        username: "customer",
        accountStatus: "active",
        passwordHash: "password",
        createdDateISO: "2026-01-01T12:00:00.000Z",
        firstName: "Demo",
        lastName: "Customer",
        email: "customer@example.com",
        phoneNumber: 15550000001,
        password: "password",
        name: "Demo Customer",
        role: "customer",
        preferredNotificationChannel: "email",
        numberOfServiceRequests: 0,
      },
      {
        id: "u_manager_1",
        userId: 2,
        username: "manager",
        accountStatus: "active",
        passwordHash: "password",
        createdDateISO: "2026-01-01T12:00:00.000Z",
        firstName: "Demo",
        lastName: "Manager",
        email: "manager@example.com",
        phoneNumber: 15550000002,
        password: "password",
        name: "Demo Manager",
        role: "manager",
        managerPermissions: true,
        salary: 65000,
      },
    ],
    quotes: [],
    bookings: [],
    payments: [],
    feedback: [],
    availability: [
      // Alex - works weekdays, mornings
      { id: "av_1", employeeName: "Alex", dayOfWeek: "Monday", shift: "morning" },
      { id: "av_2", employeeName: "Alex", dayOfWeek: "Tuesday", shift: "morning" },
      { id: "av_3", employeeName: "Alex", dayOfWeek: "Wednesday", shift: "all_day" },
      { id: "av_4", employeeName: "Alex", dayOfWeek: "Thursday", shift: "morning" },
      { id: "av_5", employeeName: "Alex", dayOfWeek: "Friday", shift: "morning" },
      // Jordan - works evenings and weekends
      { id: "av_6", employeeName: "Jordan", dayOfWeek: "Monday", shift: "evening" },
      { id: "av_7", employeeName: "Jordan", dayOfWeek: "Wednesday", shift: "evening" },
      { id: "av_8", employeeName: "Jordan", dayOfWeek: "Friday", shift: "evening" },
      { id: "av_9", employeeName: "Jordan", dayOfWeek: "Saturday", shift: "all_day" },
      { id: "av_10", employeeName: "Jordan", dayOfWeek: "Sunday", shift: "all_day" },
      // Sam - part-time, Tue/Thu/Sat
      { id: "av_11", employeeName: "Sam", dayOfWeek: "Tuesday", shift: "all_day" },
      { id: "av_12", employeeName: "Sam", dayOfWeek: "Thursday", shift: "all_day" },
      { id: "av_13", employeeName: "Sam", dayOfWeek: "Saturday", shift: "morning" },
    ],
    timeSlots: [],
    inventory: [
      {
        id: "inv_1",
        itemId: 1,
        itemType: "Dollies",
        quantity: 5,
        itemCost: 120,
        name: "Dollies",
        unit: "pcs",
      },
      {
        id: "inv_2",
        itemId: 2,
        itemType: "Blankets",
        quantity: 32,
        itemCost: 15,
        name: "Blankets",
        unit: "pcs",
      },
      {
        id: "inv_3",
        itemId: 3,
        itemType: "Straps",
        quantity: 18,
        itemCost: 22,
        name: "Straps",
        unit: "pcs",
      },
    ],
    notifications: [],
    activeUserId: "u_customer_1",
  };
};
