import type { Metadata } from "next";
import "./globals.css";
import { AppStoreProvider } from "@/src/state/AppStore";
import { AppHeader } from "@/src/components/AppHeader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <AppStoreProvider>
          <AppHeader />
          {children}
        </AppStoreProvider>
      </body>
    </html>
  );
}
